name: Gradle releases

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build MultiMC4Forge
        run: chmod +x gradlew && ./gradlew build -Pversion=${{ steps.vars.outputs.sha_short }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.vars.outputs.sha_short }}"
          prerelease: true
          title: "MultiMC4Forge ${{ steps.vars.outputs.sha_short }}"
          files: |
            user-interface/build/libs/multimc4forge-*.jar